// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr2oUaQ71-hLBYSAnZKIKgqUFv0FLlX9M',
    appId: '1:994906987649:web:090dca81ecca0714efc180',
    messagingSenderId: '994906987649',
    projectId: 'todoflutter-67326',
    authDomain: 'todoflutter-67326.firebaseapp.com',
    storageBucket: 'todoflutter-67326.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfThIswkOopXJ5LaII4ZxeJcRDTbfBKPI',
    appId: '1:994906987649:android:54f7a0cf4482eafcefc180',
    messagingSenderId: '994906987649',
    projectId: 'todoflutter-67326',
    storageBucket: 'todoflutter-67326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57ZeTQLQpwPGvZvJdL_YzW3ztZFdPjEc',
    appId: '1:994906987649:ios:d7ba4d843782a166efc180',
    messagingSenderId: '994906987649',
    projectId: 'todoflutter-67326',
    storageBucket: 'todoflutter-67326.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA57ZeTQLQpwPGvZvJdL_YzW3ztZFdPjEc',
    appId: '1:994906987649:ios:d7ba4d843782a166efc180',
    messagingSenderId: '994906987649',
    projectId: 'todoflutter-67326',
    storageBucket: 'todoflutter-67326.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr2oUaQ71-hLBYSAnZKIKgqUFv0FLlX9M',
    appId: '1:994906987649:web:d68de4ce7bc80a46efc180',
    messagingSenderId: '994906987649',
    projectId: 'todoflutter-67326',
    authDomain: 'todoflutter-67326.firebaseapp.com',
    storageBucket: 'todoflutter-67326.appspot.com',
  );
}
